### PR TITLE
Use options syntax for configuration

### PR DESCRIPTION
**Pull request by chrisb**
This PR provides support for OmniAuth's [setup phase](https://github.com/intridea/omniauth/wiki/Setup-Phase) to configure the Parse API headers.

### CODE REVIEW

**Comment by chrisb** [comment]
@mgates hey, sorry for the late reply -- sure, I'm happy to take it over. Let me know how you want to proceed (use my fork as canonical, or add me as a collaborator, etc.) 

Make sure to `gem owner add` me so I can push updates upstream to rubygems. Cheers!

**Comment by chrisb** [comment]
@mgates ping

**Comment by mgates** [comment]
Oh jeeze, this totally slipped my mind.

**Comment by mgates** [comment]
OK, merged, bumped the version, added you as a github contributor and pushed a new gem. I need the email you want me to add as gem contributor.

Sorry about the delay -- have fun.

**Comment by chrisb** [comment]
chris@shadow.io

-- 
Chris Bielinski
On February 27, 2015 at 11:00:50 AM, Micah Gates (notifications@github.com) wrote:

OK, merged, bumped the version, added you as a github contributor and pushed a new gem. I need the email you want me to add as gem contributor.

Sorry about the delay -- have fun.

**Comment by mgates** [comment]
Done.

**Pull request merged**
